### ISSUE TITLE
Unselecting all options of checkbox_multi generates error.

### ISSUE THREAD

**Issue by andrewlaskey** [hlashbrooke/WordPress-Plugin-Template#30]
Warning: in_array() expects parameter 2 to be array, string given in "...-admin-api.php" on line 112

It looks like when you unselect all the options in a checkbox_multi field, it is saved as an empty string, rather than an empty array. Trying to loop through the option as an array, or in this case use the in_array() test, Wordpress generates an error.

**Comment by senlin** [comment]
I am experiencing the exact same issue. I believe it is not an error, but a warning, nevertheless it shouldn't be there :)
