### ISSUE TITLE
Call the options

### ISSUE THREAD

**Issue by advokatb** [hlashbrooke/WordPress-Plugin-Template#42]
How can I call the option?
e.g.
`				array(
					'id' 			=> 'radio_buttons',
					'label'			=> __( 'Some Options', 'dvs-scissors' ),
					'description'	=> __( 'A standard set of radio buttons.', 'dvs-scissors' ),
					'type'			=> 'radio',
					'options'		=> array( 'blog' => 'Блог', 'vizitka' => 'Визитка', 'corporate' => 'Корпоративный', 'shop' => 'Магазин' ),
					'default'		=> 'batman'
				),`
so I want to call two functions with different radio buttons
`<?php if( $dvs_settings['radio_buttons'] == 'blog' ) {
    add_filter('admin_footer_text', 'change_footer_admin');
 } elseif( $dvs_settings['radio_buttons'] == 'vizitka' ) {
    add_action( 'admin_menu', 'my_footer_shh' );
 } // end if ?>
`
What am I doing wrong?

**Comment by carl-alberto** [comment]
I also had to dig on the code so I can figure out how to call the settings, hopefully the PR that I submitted to @hlashbrooke to add an additional description in the readme file on how to use the Settings API included in his plugin template

https://github.com/hlashbrooke/WordPress-Plugin-Template/pull/45

Basically, when you declare your settings around line:108 of https://github.com/hlashbrooke/WordPress-Plugin-Template/blob/master/includes/class-wordpress-plugin-template-settings.php

`	private function settings_fields () {

		$settings['standard'] = array(
			'title'					=> __( 'API settings', 'plugin_name' ),
			'description'			=> __( 'desc.', 'plugin-name-lang' ),
			'fields'				=> array(
				array(
					'id' 			=> 'text_field',
					'label'			=> __( 'text_field' , 'plugin-name-lang' ),
					'description'	=> __( 'desc' ),
					'type'			=> 'text',
					'default'		=> '',
					'placeholder'	=> __( '', 'plugin-name-lang' )
				),` ...

you can call it by using `get_option('wpt_text_field')`

Take note that by default, this plugin is using a prefix of `wpt_` before the id that you will be calling, you can override that value by changing it under the `__construct` function `$this->base` variable;

**Comment by hlashbrooke** [comment]
I've merged your PR - thanks @carl-alberto :)
