### ISSUE TITLE
WP CS compliant and Travis integration

### ISSUE THREAD

**Issue by carl-alberto** [hlashbrooke/WordPress-Plugin-Template#56]
Hi Hugh,

I really like your project and this helped me a lot in building plugins. I was looking into making it more WP CS compliant https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards and put some Travis checks. I hope your not too busy maintaining this project, maybe I can help out on the maintenance?

**Comment by hlashbrooke** [comment]
Making this more standards compliant would be great! It's been a while since I actually looked at this code, but I'm fairly sure it is mostly WP CS compliant already. That being said, if there's any way to improve it on that front then I'm happy to accept PRs :)

**Comment by carl-alberto** [comment]
Awesome, I could get started adding with a travis check with phpcs, jshint and jscs https://github.com/hlashbrooke/WordPress-Plugin-Template/pull/57

**Comment by carl-alberto** [comment]
@jonathanbossenger Referencing the new PR against this issue for our reference https://github.com/hlashbrooke/WordPress-Plugin-Template/pull/75

Thanks!

**Comment by carl-alberto** [comment]
We can also address the PR here: https://github.com/hlashbrooke/WordPress-Plugin-Template/pull/57

I'll close this pending PR https://github.com/hlashbrooke/WordPress-Plugin-Template/pull/63 in favor of the new PR that I have above

**Comment by jonathanbossenger** [comment]
Merged #76 :tada:
