### ISSUE TITLE
Installer error: "fatal: Too many arguments."

### ISSUE THREAD

**Issue by seezee** [hlashbrooke/WordPress-Plugin-Template#77]
Downloaded the script, made it executable, moved it to `/usr/local/bin` & ran it. Got error `fatal: Too many arguments.` Using MacOS Mojave. Other output below:

    Removing git files...
    rm: README.md: No such file or directory
    rm: build-plugin.sh: No such file or directory
    rm: changelog.txt: No such file or directory
    Updating plugin files...
    mv: rename wordpress-plugin-template.php to wp-foft-loader.php: No such file or directory
    cp: wp-foft-loader.php: No such file or directory
    sed: wp-foft-loader.tmp: No such file or directory
    rm: wp-foft-loader.tmp: No such file or directory
    cp: readme.txt: No such file or directory
    sed: readme.tmp: No such file or directory
    rm: readme.tmp: No such file or directory
    /usr/local/bin/build.plugin.sh: line 66: cd: lang: No such file or directory
    mv: rename wordpress-plugin-template.pot to wp-foft-loader.pot: No such file or directory
    cp: wp-foft-loader.pot: No such file or directory
    sed: wp-foft-loader.tmp: No such file or directory
    rm: wp-foft-loader.tmp: No such file or directory
    /usr/local/bin/build.plugin.sh: line 86: cd: ../includes: No such file or directory
    mv: rename class-wordpress-plugin-template.php to class-wp-foft-loader.php: No such file or directory
    cp: class-wp-foft-loader.php: No such file or directory
    sed: class-wp-foft-loader.tmp: No such file or directory
    rm: class-wp-foft-loader.tmp: No such file or directory
    mv: rename class-wordpress-plugin-template-settings.php to class-wp-foft-loader-settings.php: No such file or directory
    cp: class-wp-foft-loader-settings.php: No such file or directory
    sed: class-wp-foft-loader-settings.tmp: No such file or directory
    rm: class-wp-foft-loader-settings.tmp: No such file or directory
    /usr/local/bin/build.plugin.sh: line 117: cd: lib: No such file or directory
    mv: rename class-wordpress-plugin-template-post-type.php to class-wp-foft-loader-post-type.php: No such file or directory
    cp: class-wp-foft-loader-post-type.php: No such file or directory
    sed: class-wp-foft-loader-post-type.tmp: No such file or directory
    rm: class-wp-foft-loader-post-type.tmp: No such file or directory
    mv: rename class-wordpress-plugin-template-taxonomy.php to class-wp-foft-loader-taxonomy.php: No such file or directory
    cp: class-wp-foft-loader-taxonomy.php: No such file or directory
    sed: class-wp-foft-loader-taxonomy.tmp: No such file or directory
    rm: class-wp-foft-loader-taxonomy.tmp: No such file or directory
    mv: rename class-wordpress-plugin-template-admin-api.php to class-wp-foft-loader-admin-api.php: No such file or directory
    cp: class-wp-foft-loader-admin-api.php: No such file or directory
    sed: class-wp-foft-loader-admin-api.tmp: No such file or directory
    rm: class-wp-foft-loader-admin-api.tmp: No such file or directory

**Comment by jonathanbossenger** [comment]
@seezee the script is not meant to be run from the /usr/local/bin directory, it's meant to be run from inside the plugin template directory.

**Comment by seezee** [comment]
> @seezee the script is not meant to be run from the /usr/local/bin directory, it's meant to be run from inside the plugin template directory.

Thank you; that was my mistake.
