### ISSUE TITLE
Fatal Error: Cannot access private property $admin in class-wordpress-plugin-template-settings.php on line 367

### ISSUE THREAD

**Issue by seezee** [hlashbrooke/WordPress-Plugin-Template#80]
Fatal error: Uncaught Error: Cannot access private property WordPress_Plugin_Template::$admin in /app/public/wp-content/plugins/~WordPress-Plugin-Template/includes/class-wordpress-plugin-template-settings.php on line 367

Commenting out line 31 of class-wordpress-plugin-template.php fixes the error.

EDIT: I came up with this fix. Added this to main Class file:

	/**
	 * Admin function.
	 *
	 * @var     object
	 * @access  public
	 * @since   1.0.0
	 */
	public function admin() {
		$this->admin = $admin;
	}

And changed Class _Settings line from this:
	`array( $this->parent->admin, 'display_field' ),`
to this:
	`array( $this->parent->admin(), 'display_field' ),`

Once I figure out how to create a pull request I'll do so.

**Comment by jonathanbossenger** [comment]
@seezee I created #82 as a fix for this, and also to film the process of creating a pull request. I'll share the video URL with you on the other issue shortly.
