### ISSUE TITLE
How to display html on external pages of the site?

### ISSUE THREAD

**Issue by karpinskyi** [hlashbrooke/WordPress-Plugin-Template#83]
How to display this code on the pages of the site?
echo '<script>alert("'.get_option('wpt_text_block').'");</script>';
How to do it correctly, according to the architecture of this plugin?

I can't understand the structure of the plugin. Do I need to create a file for an external template, or do I need to create a function in the class?
Help me please.

**Comment by jonathanbossenger** [comment]
@karpinskyi this repository is a plugin template, which you can use as a foundation for building your own WordPress plugins. You will however need to have a good understanding of how to build your own WordPress plugins in the first place, to be able to make use of this template.

I recommend reading the [WordPress Plugin Developer Handbook](https://developer.wordpress.org/plugins/)

As to your specific question, you could probably do so by way of a [shortcode](https://developer.wordpress.org/plugins/shortcodes/)

**Comment by karpinskyi** [comment]
I want to create my own plugin. I don't need a shortcode. I know php js. But I can't figure out where to add this code to output it.
