### ISSUE TITLE
Custom Post Type $args, Taxonomy $args

### ISSUE THREAD

**Issue by Apiru** [hlashbrooke/WordPress-Plugin-Template#98]
Hello,

I want use this plugin API for set args for CPT or Taxonomy.
I know classic way from wordpress, but solution from plugin look better.

I dont know how to use this:
`{$post_type}_register_args`
or this:
`{$taxonomy}_register_args`

Could someone give me an example code please ?

Thanks all for help

**Comment by cornelRaiu** [comment]
@rucilos `{$post_type}` stands for your CPT slug. 

If your CPT slug is `product`, then the filter you have to use will be `product_register_args`.

Same goes for the taxonomies.

I hope that helped
